name: driver
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_phoenix: ^1.1.1
  flutter_bloc: ^8.1.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  flutter_local_notifications: ^15.1.0+1
  firebase_messaging: ^14.6.5
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.1
  toast: ^0.3.0
  shimmer_animation: ^2.1.0+1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.1.2
  signature: ^5.4.0
  google_maps_flutter: ^2.4.0
  location: ^5.0.2+1
  awesome_notifications: ^0.7.4+1
  dio: ^5.3.2
  # TODO: Remove this branch after official release with the fix is published
  background_location: ^0.11.8
  wakelock: ^0.6.1+2

dependency_overrides:
  intl: ^0.18.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon1.png"

flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Bold.ttf
  assets:
    - assets/