// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8zXQwEqQFICc-6LkkW53xtCB1PtlWlSw',
    appId: '1:417010229849:web:114cdc0aa75f98aeb00748',
    messagingSenderId: '417010229849',
    projectId: 'bulkotest',
    authDomain: 'bulkotest.firebaseapp.com',
    databaseURL: 'https://bulkotest-default-rtdb.firebaseio.com',
    storageBucket: 'bulkotest.appspot.com',
    measurementId: 'G-DLY1HG98W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY-E2b8T6VdhTdr4rXZ3BvjAvQIhaYZ54',
    appId: '1:417010229849:android:e8c01c2aea00afe1b00748',
    messagingSenderId: '417010229849',
    projectId: 'bulkotest',
    databaseURL: 'https://bulkotest-default-rtdb.firebaseio.com',
    storageBucket: 'bulkotest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgKxdixnPF9MPa1mwwINqujC-heJOTreg',
    appId: '1:417010229849:ios:078e753a5fc34897b00748',
    messagingSenderId: '417010229849',
    projectId: 'bulkotest',
    databaseURL: 'https://bulkotest-default-rtdb.firebaseio.com',
    storageBucket: 'bulkotest.appspot.com',
    androidClientId: '417010229849-7jsai1b0qun10t9g8q5bnldocqe8doab.apps.googleusercontent.com',
    iosClientId: '417010229849-auemlto26kkfrqp4jdbr1dmmnbp5rq7v.apps.googleusercontent.com',
    iosBundleId: 'com.bitinfusion.bulko.delivery',
  );
}
